window.resources = {
  users: {
    title: 'Usuarios',
    hint: 'Personas con acceso',
    endpoint: '/api/user',
    roles: ['admin'],
    idKey: 'id_usuario',
    columns: ['id_usuario', 'nombre', 'apellido1', 'email', 'telefono', 'rol'],
    fields: [
      ['nombre', 'Nombre', 'text', true],
      ['apellido1', 'Primer apellido', 'text', true],
      ['apellido2', 'Segundo apellido', 'text', false],
      ['email', 'Email', 'email', true],
      ['password', 'Password', 'password', true],
      ['telefono', 'Teléfono', 'tel', false],
      ['rol', 'Rol', 'select', false, ['admin', 'propietario', 'inquilino']],
      ['activo', 'Activo', 'select', false, ['1', '0']],
    ],
  },
  tenantUserData: {
    title: 'Datos usuario',
    hint: 'Tu información personal',
    endpoint: '/api/tenant/me',
    roles: ['inquilino'],
    readOnlyRoles: ['inquilino'],
    idKey: 'id_inquilino',
    columns: ['nombre', 'apellido1', 'apellido2', 'email', 'telefono', 'identificacion', 'numero_documento', 'nacionalidad'],
    fields: [],
  },
  tenants: {
    title: 'Inquilinos',
    titleByRole: {
      inquilino: 'Vivienda',
    },
    hint: 'Fichas documentales',
    hintByRole: {
      inquilino: 'Tu vivienda y habitación',
    },
    endpoint: '/api/tenant',
    endpointByRole: {
      inquilino: '/api/tenant/me',
    },
    roles: ['admin', 'propietario', 'inquilino'],
    readOnlyRoles: ['inquilino'],
    idKey: 'id_inquilino',
    columns: ['nombre', 'apellido1', 'apellido2', 'email', 'telefono', 'identificacion', 'numero_documento', 'fecha_entrada'],
    columnsByRole: {
      inquilino: [
        'nombre_vivienda',
        'direccion',
        'localidad',
        'nombre_habitacion',
        'tipo_habitacion',
        'precio',
        'fecha_entrada',
      ],
    },
    fields: [
      ['id_usuario', 'Id usuario', 'number', true],
      ['nacionalidad', 'Nacionalidad', 'text', false],
      ['identificacion', 'Identificación', 'select', true, ['dni', 'nie', 'pasaporte']],
      ['numero_documento', 'Núm. documento', 'text', true],
    ],
  },
  tenantContracts: {
    title: 'Contratos',
    hint: 'Tus documentos de contrato',
    endpoint: '/api/tenant/me',
    roles: ['inquilino'],
    readOnlyRoles: ['inquilino'],
    idKey: 'id_inquilino',
    columns: ['id_inquilino', 'nombre_vivienda', 'nombre_habitacion', 'fecha_entrada', 'fecha_salida', 'contrato_firmado_archivo'],
    fields: [],
  },
  owners: {
    title: 'Propietarios',
    hint: 'Datos de facturación',
    endpoint: '/api/owner',
    roles: ['admin'],
    idKey: 'id_propietario',
    columns: ['nombre', 'apellido1', 'email', 'nombre_empres', 'cif', 'iban'],
    fields: [
      ['id_usuario', 'Id usuario', 'number', true],
      ['nombre_empres', 'Empresa', 'text', false],
      ['cif', 'Cif', 'text', false],
      ['iban', 'Iban', 'text', false],
      ['observaciones', 'Observaciones', 'textarea', false],
    ],
  },
  houses: {
    title: 'Viviendas',
    hint: 'Activos disponibles',
    endpoint: '/api/house',
    roles: ['admin', 'propietario'],
    idKey: 'id_vivienda',
    columns: ['nombre', 'direccion', 'localidad', 'provincia', 'codigo_postal', 'activa'],
    fields: [
      ['nombre', 'Nombre', 'text', true],
      ['direccion', 'Dirección', 'text', true],
      ['localidad', 'Localidad', 'text', true],
      ['provincia', 'Provincia', 'text', true],
      ['codigo_postal', 'Código postal', 'text', false],
      ['descripcion', 'Descripción', 'textarea', false],
      ['activa', 'Activa', 'select', false, ['true', 'false']],
    ],
  },
  rooms: {
    title: 'Habitaciones',
    hint: 'Unidades alquilables',
    endpoint: '/api/room',
    roles: ['admin', 'propietario'],
    idKey: 'id_habitacion',
    columns: ['nombre_vivienda', 'nombre', 'tipo', 'numero_camas', 'precio', 'camas_libres'],
    disableRowMutations: true,
    fields: [
      ['id_vivienda', 'Vivienda', 'number', true],
      ['nombre', 'Nombre', 'text', true],
      ['tipo', 'Tipo', 'select', false, ['grande', 'mediana', 'pequena']],
      ['numero_camas', 'Camas', 'number', false],
      ['precio', 'Precio habitación', 'number', false],
      ['activa', 'Activa', 'select', false, ['true', 'false']],
    ],
  },
  ownerExpenses: {
    title: 'Gastos propietario',
    titleByRole: {
      propietario: 'Gastos',
    },
    hint: 'Gastos asociados a propietarios y viviendas',
    hintByRole: {
      propietario: 'Gastos de tus viviendas',
    },
    endpoint: '/api/owner-expense',
    roles: ['admin', 'propietario'],
    idKey: 'id_gasto_propietario',
    columns: ['gasto_de', 'nombre_vivienda', 'concepto', 'importe', 'fecha', 'tipo', 'estado', 'pagado_por'],
    fields: [
      ['id_propietario', 'Propietario', 'number', true],
      ['id_vivienda', 'Vivienda', 'number', false],
      ['concepto', 'Concepto', 'text', true],
      ['descripcion', 'Descripción', 'textarea', false],
      ['importe', 'Importe', 'number', true],
      ['fecha', 'Fecha', 'text', true],
      ['tipo', 'Tipo', 'select', false, ['mantenimiento', 'reparacion', 'comision', 'impuesto', 'seguro', 'hipoteca', 'otros']],
      ['estado', 'Estado', 'select', false, ['pendiente', 'pagado', 'cancelado']],
      ['pagado_por', 'Pagado por', 'select', false, ['propietario', 'inquilino', 'vivienda']],
      ['computa_beneficio', 'Computa beneficio', 'select', false, ['true', 'false']],
    ],
    fieldsByRole: {
      propietario: [
        ['id_vivienda', 'Vivienda', 'number', false],
        ['concepto', 'Concepto', 'text', true],
        ['descripcion', 'Descripción', 'textarea', false],
        ['importe', 'Importe', 'number', true],
        ['fecha', 'Fecha', 'text', true],
        ['tipo', 'Tipo', 'select', false, ['mantenimiento', 'reparacion', 'comision', 'impuesto', 'seguro', 'hipoteca', 'otros']],
        ['estado', 'Estado', 'select', false, ['pendiente', 'pagado', 'cancelado']],
        ['pagado_por', 'Pagado por', 'select', false, ['propietario', 'inquilino', 'vivienda']],
        ['computa_beneficio', 'Computa beneficio', 'select', false, ['true', 'false']],
      ],
    },
  },
  ownerLiquidations: {
    title: 'Contabilidad',
    hint: 'Libro diario',
    hintByRole: {
      propietario: 'Libro diario de tus viviendas',
    },
    endpoint: '/api/owner-liquidation',
    roles: ['admin', 'propietario'],
    readOnlyRoles: ['admin', 'propietario'],
    idKey: 'id_liquidacion',
    columns: [
      'id_liquidacion',
      'nombre_vivienda',
      'mes',
      'anio',
      'gastos',
      'ingresos',
    ],
    computedColumns: {
      gastos: ['gastos_vivienda', 'gastos_recuperados', 'pagos_pendientes'],
      ingresos: ['ingresos_alquiler'],
    },
    disableRowMutations: true,
    detail: true,
    fields: [],
  },
  payments: {
    title: 'Pagos',
    titleByRole: {
      inquilino: 'Recibos',
    },
    hint: 'Listado de mensualidades y gastos',
    hintByRole: {
      inquilino: 'Tus recibos',
    },
    endpoint: '/api/tenant-payment',
    endpointByRole: {
      inquilino: '/api/tenant-payment/me',
    },
    roles: ['admin', 'propietario', 'inquilino'],
    readOnlyRoles: ['inquilino'],
    idKey: 'payment_key',
    columns: ['nombre_inquilino', 'nombre_vivienda', 'concepto', 'parte_proporcional', 'estado_pago', 'importe_pendiente', 'fecha_recibo'],
    columnsByRole: {
      inquilino: ['id_pago_inquilino', 'id_inquilino', 'concepto', 'importe', 'mes', 'anio'],
    },
    fields: [
      ['id_inquilino', 'Id inquilino', 'number', true],
      ['concepto', 'Concepto', 'text', true],
      ['importe', 'Importe', 'number', true],
      ['mes', 'Mes', 'number', true],
      ['anio', 'Año', 'number', true],
      ['pagado_por', 'Pagado por', 'select', false, ['propietario', 'inquilino', 'vivienda']],
    ],
  },
  deposits: {
    title: 'Fianzas',
    hint: 'Fianzas de inquilinos',
    endpoint: '/api/tenant-deposit',
    endpointByRole: {
      inquilino: '/api/tenant-deposit/me',
    },
    roles: ['admin', 'propietario', 'inquilino'],
    readOnlyRoles: ['inquilino'],
    idKey: 'id_fianza',
    columns: ['nombre_inquilino', 'nombre_vivienda', 'importe', 'estado', 'importe_cobrado', 'importe_devuelto', 'importe_compensado', 'importe_retenido', 'importe_disponible', 'fecha_fianza'],
    columnsByRole: {
      inquilino: ['importe', 'estado', 'importe_cobrado', 'importe_devuelto', 'importe_compensado', 'importe_retenido', 'importe_disponible', 'fecha_fianza'],
    },
    fields: [],
  },
  expenses: {
    title: 'Gastos',
    titleByRole: {
      inquilino: 'Gastos',
    },
    hint: 'Gastos de inquilino',
    hintByRole: {
      inquilino: 'Gastos de tu vivienda',
    },
    endpoint: '/api/tenant-expense',
    endpointByRole: {
      inquilino: '/api/tenant-expense/me',
    },
    roles: ['admin', 'inquilino'],
    readOnlyRoles: ['inquilino'],
    idKey: 'id_gasto',
    columns: ['id_gasto', 'nombre_vivienda', 'tipo', 'descripcion', 'importe_total', 'fecha_inicio', 'fecha_fin', 'estado', 'pagado_por'],
    fields: [
      ['id_inquilino', 'Id inquilino', 'number', true],
      ['concepto', 'Concepto', 'text', true],
      ['importe', 'Importe', 'number', true],
      ['mes', 'Mes', 'number', true],
      ['anio', 'Año', 'number', true],
    ],
  },
};

window.resourceMenuActions = {
  tenants: [
    {
      action: 'create',
      hint: 'Crear nueva ficha de inquilino',
    },
    {
      action: 'delete',
      hint: 'Selecciona un inquilino y pulsa Borrar',
    },
  ],
  houses: [
    {
      action: 'create',
      hint: 'Crear nueva vivienda',
    },
    {
      action: 'update',
      hint: 'Selecciona una vivienda y pulsa Editar',
    },
    {
      action: 'delete',
      hint: 'Selecciona una vivienda y pulsa Borrar',
    },
  ],
  ownerExpenses: [
    {
      action: 'create',
      hint: 'Crear nuevo gasto',
    },
  ],
  statistics: [
    {
      action: 'bar',
      hint: 'Gráfico de barras',
    },
    {
      action: 'line',
      hint: 'Gráfico de línea',
    },
    {
      action: 'pie',
      hint: 'Gráfico circular',
    },
  ],
};
